#!/bin/bash
# Author: Iian Douglas <centos@1n6.org.uk>

# Test znew - converts .Z files to .gz
# Create a test file

# Skip if after CentOS 8
if [ "$centos_ver" -gt "8" ]
then
  t_Log "ncompress not present post-c8 => SKIP"
  t_CheckExitStatus 0
  exit $PASS
fi

t_Log "Running $0 -  Testing znew"

TESTFILE=/var/tmp/znew.txt
rm $TESTFILE* &>/dev/null

ls /usr/bin >$TESTFILE
compress $TESTFILE 

znew $TESTFILE.Z
t_CheckExitStatus $?
