#!/bin/bash
# Author: Iain Douglas <centos@1n6.org.uk>

t_Log "Running $0"

# Check that the testgroup exists with GID 2010
grep -q "testgroup:x:2010:testshadow" /etc/group || { t_Log "FAIL Test group doesn't exist"; exit $FAIL; }

echo "Changing GID for group testgroup to 2011"
groupmod -g 2011 testgroup
t_CheckExitStatus $?
